name: corruption_reporter
description: "A secure, offline-first mobile app for reporting corruption incidents with encrypted data storage and real-time sync."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Local Storage & Database
  sqflite: ^2.3.0
  drift: ^2.13.1
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2

  # Network & API
  dio: ^5.3.2
  connectivity_plus: ^5.0.1
  retry: ^3.1.2

  # Security & Encryption
  crypto: ^3.0.3
  encrypt: ^5.0.1
  flutter_secure_storage: ^9.0.0

  # Media & File Handling
  camera: ^0.10.5+5
  video_player: ^2.7.2
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  permission_handler: ^11.0.1

  # Location & GPS
  geolocator: ^10.1.0
  geocoding: ^2.1.1

  # UI Components
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  photo_view: ^0.14.0
  flutter_staggered_grid_view: ^0.7.0

  # Utilities
  intl: ^0.18.1
  uuid: ^4.1.0
  device_info_plus: ^9.1.0
  package_info_plus: ^4.2.0

  # Push Notifications
  firebase_core: ^2.17.0
  firebase_messaging: ^14.7.3
  flutter_local_notifications: ^16.1.0

  # Form Validation
  formz: ^0.6.1

  # JSON Handling
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  drift_dev: ^2.13.2

  # Linting
  flutter_lints: ^3.0.0

  # Testing
  bloc_test: ^9.1.4
  mocktail: ^1.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logo/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700