name: emergency_response_mobile
description: Emergency Response Platform Mobile App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # Core dependencies
  cupertino_icons: ^1.0.2

  # State management
  provider: ^6.0.5
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9

  # HTTP and networking
  dio: ^5.3.2
  connectivity_plus: ^5.0.1

  # Location services
  geolocator: ^10.1.0
  location: ^5.0.3
  google_maps_flutter: ^2.5.0

  # Media and camera
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  video_player: ^2.7.2
  record: ^5.0.4

  # Storage and encryption
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  crypto: ^3.0.3

  # Authentication
  local_auth: ^2.1.6

  # Push notifications
  firebase_core: ^2.17.0
  firebase_messaging: ^14.7.3
  flutter_local_notifications: ^16.2.0

  # UI components
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  lottie: ^2.7.0
  shimmer: ^3.0.0

  # QR code
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0

  # Background tasks
  workmanager: ^0.5.2

  # Permissions
  permission_handler: ^11.0.1

  # Utils
  uuid: ^4.1.0
  intl: ^0.18.1
  logger: ^2.0.2+1
  package_info_plus: ^4.2.0
  device_info_plus: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/sounds/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700